# Generated by Django 3.1.1 on 2020-11-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20201115_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_follower',
            field=models.BooleanField(default=False),
        ),
    ]
